"""create events and outbox

Revision ID: fde5a468e49a
Revises: 
Create Date: 2026-01-15 17:07:37.847254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fde5a468e49a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_event_id', sa.UUID(), nullable=True),
    sa.Column('deduplication_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_deduplication_key'), 'events', ['deduplication_key'], unique=False)
    op.create_index(op.f('ix_events_service'), 'events', ['service'], unique=False)
    op.create_index(op.f('ix_events_source_event_id'), 'events', ['source_event_id'], unique=False)
    op.create_table('outbox_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_messages_attempts'), 'outbox_messages', ['attempts'], unique=False)
    op.create_index(op.f('ix_outbox_messages_status'), 'outbox_messages', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_messages_topic'), 'outbox_messages', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_messages_topic'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_status'), table_name='outbox_messages')
    op.drop_index(op.f('ix_outbox_messages_attempts'), table_name='outbox_messages')
    op.drop_table('outbox_messages')
    op.drop_index(op.f('ix_events_source_event_id'), table_name='events')
    op.drop_index(op.f('ix_events_service'), table_name='events')
    op.drop_index(op.f('ix_events_deduplication_key'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
